steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE}', '.']

images: ['${_IMAGE}']

substitutions:
  _IMAGE: '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}/${REPO_NAME}:${TAG_NAME:-${SHORT_SHA}}'