apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: 1st-app
      context: deployment
  googleCloudBuild:
    projectId: devops-labs-322408
deploy:
  kubectl:
    manifests:
      - kubernetes/*
portForward:
  - resourceType: deployment
    resourceName: 1st-app
    port: 8080
    localPort: 80