apiVersion: skaffold/v2beta7
kind: Config
build:
  artifacts:
    - image: for-cb
      context: deployment
  googleCloudBuild:
    projectId: devops-labs-322408
deploy:
  docker:
      dockerfile: "Dockerfile"