apiVersion: apps/v1
kind: Deployment
metadata:
  name: 1st-app
  namespace: deployment
  labels:
    app: 1st-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1st-app
  template:
    metadata:
      labels:
        app: 1st-app
    spec:
      containers:
        - name: 1st-app
          image: 1st-app
          ports:
            - containerPort: 8080
