apiVersion: v1
kind: Service
metadata:
  name: for-test-app-lb-service
spec:
  selector:
    app: for-test-app
  ports:
  - nodePort: 30693
    port: 80
    protocol: TCP
    targetPort: 80
  externalTrafficPolicy: Cluster
  type: LoadBalancer