apiVersion: v1
kind: Service
metadata:
  name: for-test-app-service
  namespace: deployment
spec:
  selector:
    app: for-test-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  externalTrafficPolicy: Cluster
  type: LoadBalancer